services:
  - type: web
    name: canadasabeel_wp
    env: node
    buildCommand: |
      apt-get update && apt-get install -y chromium chromium-driver
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true